name: Deploy NIC-ERP no Servidor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Baixar código fonte atualizado
        uses: actions/checkout@v4

      - name: Sincronização e Build (Padrão apps_core)
        run: |
          CAMINHO_SERVIDOR="/opt/nic-labs/core/n-hub"
          
          # 1. Sincroniza apenas o código fonte do projeto
          rsync -av --exclude='.git/' ./ $CAMINHO_SERVIDOR/
          
          # 2. Vai para a pasta do projeto (compose.yml está na raiz do repo)
          cd $CAMINHO_SERVIDOR
          
          # 3. Build e deploy
          docker compose build --no-cache
          docker compose up -d --remove-orphans
          
      - name: Limpar lixo do Docker
        run: docker image prune -f && docker builder prune -f