name: Deploy N-HUB no Servidor

on:
  push:
    branches:
      - main  # ou master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Baixar código fonte atualizado
        uses: actions/checkout@v4

      - name: Sincronizar arquivos e reiniciar Docker
        run: |
          # Define a nova pasta dedicada no servidor
          CAMINHO_SERVIDOR="/opt/nic-labs/core/n-hub"

          # Garante que a pasta existe (cria se não existir)
          mkdir -p $CAMINHO_SERVIDOR

          # Copia os arquivos recém-baixados para a pasta oficial
          rsync -av --exclude='.git/' ./ $CAMINHO_SERVIDOR/

          # Entra na pasta do servidor
          cd $CAMINHO_SERVIDOR

          # Roda o docker compose usando o nome de arquivo customizado que você criou
          # Removemos os nomes dos containers do final para ele subir o banco e o pgadmin também, caso não estejam rodando
          docker compose -f compose-09-nhub.yml up -d --build
          
      - name: Limpar lixo do Docker
        run: docker image prune -f